/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trainsofsheffield;

import trainsofsheffield.views.LoginFrame;

public class App {
    public static void main(String[] args) {
        new LoginFrame("Login", null,true);
    }
}
